---
title: ""
output: html_document
---

## Welcome!

This page contains material and instructions for the session "Population dynamics" on the EERCV course. 

**Before the session**, please make sure that you have [R](https://www.r-project.org/) and [RStudio](https://rstudio.com/products/rstudio/)
, as well as the packages `popbio` (for demographic analysis) and `knitr` (for visual stuff) installed on your computer. Please also make sure to **bring your computer to both the morning and the afternoon session** as we will switch between lecture and practical exercises throughout the day.

*This is a temporary webpage so save anything that you want to keep to your personal computer* (for example by printing the pages to a pdf-file)

### Links to practical exercises

[Population Projections](Activity/PopulationProjection20.html)  

[Sensitivities and elasticities](Activity/SensitivitiesAndElasticities20.html)  

[Population viability analysis (PVA)](Activity/PopulationViabilityAnalysis20.html)  

If you want an extra exercise, try performing a [count-based PVA for the Yellowstone grizzly population](http://www.montana.edu/screel/teaching/bioe-440r-521/course-outline/count-based-PVA-grizzly-data.R)

### Lecture slides  

... will be uploaded here

```{r, include=FALSE, eval=FALSE}

Here's the [lecture](). 

```

### Assignment  

The assignment is included in the instructions for [Population Projections](Activity/PopulationProjection20.html) and [Sensitivities and elasticities](Activity/SensitivitiesAndElasticities20.html). Hand in the the assignment by 28 February. 



